<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DineshManoharan" failures="1" tests="15" name="runner.ExamRunner" time="182.110" errors="6" timestamp="2024-04-22T14:15:34 IST" skipped="0">
  <testcase classname="runner.ExamRunner" name="runScenario" time="6.344"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="8.125">
    <error message="Enter irrelevant answer how it provide marks" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Enter irrelevant answer how it provide marks
at stepDefinitions.ExamModule.if_its_allow_its_bug(ExamModule.java:342)
at ✽.If its allow its bug.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:64)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="8.325">
    <error message="Dont allow negative values in mark fiels" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Dont allow negative values in mark fiels
at stepDefinitions.ExamModule.check_the_error_message_shows_or_not_related_to_mark_in_exam_module(ExamModule.java:314)
at ✽.Check the error message shows or not related to mark in exam module.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:59)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="13.448">
    <error message="Submit and add button didn&#039;t work properly" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Submit and add button didn't work properly
at stepDefinitions.ExamModule.click_submit_and_add_icon_and_check_how_it_behave(ExamModule.java:251)
at ✽.Click submit and add icon and check how it behave.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:39)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="16.308"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="15.045"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="20.024"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="25.179">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;/html/body/div[3]/div/div[2]/div/div[2]/div/div/div[2]/button[2]&quot;}
  (Session info: chrome=124.0.6367.61)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.11.0&#039;, revision: &#039;040bc5406b&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;19.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7ec4ccb6b4610067946895b2ee44b642, findElement {using=xpath, value=/html/body/div[3]/div/div[2]/div/div[2]/div/div/div[2]/button[2]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.61, chrome: {chromedriverVersion: 124.0.6367.60 (8771130bd84f..., userDataDir: C:\Users\dinesh\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49300}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49300/devtoo..., se:cdpVersion: 124.0.6367.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7ec4ccb6b4610067946895b2ee44b642" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[2]/div/div[2]/div/div/div[2]/button[2]"}
  (Session info: chrome=124.0.6367.61)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7ec4ccb6b4610067946895b2ee44b642, findElement {using=xpath, value=/html/body/div[3]/div/div[2]/div/div[2]/div/div/div[2]/button[2]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.61, chrome: {chromedriverVersion: 124.0.6367.60 (8771130bd84f..., userDataDir: C:\Users\dinesh\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49300}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49300/devtoo..., se:cdpVersion: 124.0.6367.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7ec4ccb6b4610067946895b2ee44b642
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at stepDefinitions.ExamModule.click_the_yes_option_in_exam(ExamModule.java:390)
at ✽.Click the  Yes option in exam(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:77)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="4.887">
    <failure message="expected [Enter the credentials] but found [Exam ID is already exist]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Enter the credentials] but found [Exam ID is already exist]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDefinitions.ExamModule.check_how_it_behave_in_exam_page_whether_it_shows_error_message_or_not(ExamModule.java:125)
at ✽.Check how it behave in exam page whether it shows error message or not.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="8.395"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="4.508"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="14.432">
    <error message="Existing Time and date doesn&#039;t want to shows" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Existing Time and date doesn't want to shows
at stepDefinitions.ExamModule.throw_errors(ExamModule.java:221)
at ✽.Throw Errors.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:34)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ExamRunner" name="runScenario" time="22.630"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="4.923"/>
  <testcase classname="runner.ExamRunner" name="runScenario" time="9.537">
    <error message="Without date how can we schedule the exam?" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Without date how can we schedule the exam?
at stepDefinitions.ExamModule.check_its_created_or_not_in_exam_page(ExamModule.java:282)
at ✽.Check its created or not in exam page.(file:///C:/Users/dinesh/eclipse-workspace/Colleges/src/test/java/features/College12_Exam.feature:49)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.ExamRunner -->
